import Head from "next/head";
import Link from "next/link";
import { ChangeEvent } from "react";
import { useState } from "react"; // Import useState hook

export default function Home() {
  const [url, setUrl] = useState("");

  const sendPrompt = async () => {
   console.log()
  };

  const handleUrlChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUrl(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">

        <input
          className="rounded-lg"
          type="email"
          placeholder="Email"
          value={url}
        onChange={handleEmailChange}
          />


        <button
            onClick={() => sendPrompt()}
            className="cursor-pointer font-medium text-blue-600 hover:underline"
          >
            View
          </button>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          </div>
        </div>
      </main>
    </>
  );
}
