import Head from "next/head";
import Link from "next/link";
import { ChangeEvent } from "react";
import { useState } from "react"; // Import useState hook
import OpenAI from "openai";

const openai = new OpenAI({ apiKey: process.env.OPENAI_KEY, dangerouslyAllowBrowser: true });

export default function Home() {
  const [url, setUrl] = useState("");

  const sendPrompt = async () => {
   console.log(url)

   const response = await openai.chat.completions.create({
    model: "gpt-4-vision-preview",
    messages: [
      {
        role: "user",
        content: [
          { type: "text", text: `Can you tell me what's going on in this image.` },
          {
            type: "image_url",
            image_url: {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
            },
          },
        ],
      },
    ],
  });
  console.log(response);
  };

  const handleUrlChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUrl(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">

        <input
          className="rounded-lg"
          type="url"
          placeholder="URL"
          value={url}
          onChange={handleUrlChange}
          />


        <button
            onClick={() => sendPrompt()}
            className="cursor-pointer font-medium text-blue-600 hover:underline"
          >
            View
          </button>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          </div>
        </div>
      </main>
    </>
  );
}
